# Generated by Django 4.2 on 2024-03-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options_alter_stockportfolio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', help_text='Transaction type', max_length=4, verbose_name='Type')),
                ('trade_date', models.DateField(help_text='Trade date', verbose_name='Trade Date')),
                ('shares', models.PositiveIntegerField(help_text='Number of shares', verbose_name='Shares')),
                ('cost_per_share', models.DecimalField(decimal_places=2, help_text='Cost per share', max_digits=10, verbose_name='Cost per share')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Commission in dollars', max_digits=10, null=True, verbose_name='Commission')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('portfolio', models.ForeignKey(help_text='Portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='portfolio.portfolio', verbose_name='Portfolio')),
            ],
        ),
    ]
