# Generated by Django 4.2 on 2024-03-04 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'verbose_name': 'Stock Transaction', 'verbose_name_plural': 'Stock Transactions'},
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date Created', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date Modified', verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='shares',
            field=models.DecimalField(decimal_places=10, default=0.0, help_text='Number of shares', max_digits=16, verbose_name='Shares'),
        ),
    ]
