# Generated by Django 4.2 on 2024-03-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_options_alter_stock_country_and_more'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='stockportfolio',
            options={'verbose_name': 'Stock Portfolio', 'verbose_name_plural': 'Stock Portfolios'},
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='price_per_share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per share', max_digits=10, verbose_name='Price per share'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(help_text='Name', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='portfolio',
            field=models.ForeignKey(help_text='Portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolio', to='portfolio.portfolio', verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Purchase date', null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='quantity',
            field=models.IntegerField(help_text='Number of shares', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='stock',
            field=models.ForeignKey(blank=True, help_text='Stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolio', to='stock.stock', verbose_name='Stock'),
        ),
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together={('portfolio', 'stock')},
        ),
    ]
