# Generated by Django 4.2 on 2024-03-04 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options_alter_stockportfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date Created', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date Modified', verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date Created', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date Modified', verbose_name='Date Modified'),
        ),
    ]
