# Generated by Django 4.2 on 2024-03-04 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_options_alter_stock_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date Created', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date Modified', verbose_name='Date Modified'),
        ),
    ]
